server:
  port: 8091

eureka:
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
      service-url:
            defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: servicio-gateway-server
  cloud:
    gateway:
      routes:
      - id: usuariosModule
        uri: lb://SERVICIO-USUARIOS
        predicates:
        - Path=/api/usuarios/**
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: employeeModule
        uri: lb://FIRST-SERVICE
        predicates:
        - Path=/employee/**
      - id: consumerModule
        uri: lb://SECOND-SERVICE
        predicates:
        - Path=/consumer/**
