spring:
  application:
    name: servicio-gateway-server
  cloud:
    gateway:
      routes:
      - id: usuariosModule
        uri: lb://servicio-usuarios
        predicates:
        - Path=/api/usuarios/**
server:
  port: 8091
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
          defaultZone: http://localhost:8761/eureka
